In [1]:
import pandas as pd
import os

## Olist_Orders_Dataset

In [5]:
pd.read_csv(r"C:\Users\DELL\Downloads\olist_orders_dataset.csv")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [6]:
import pandas as pd

orders = pd.read_csv(r"C:\Users\DELL\Downloads\olist_orders_dataset.csv")

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [7]:
orders.shape

(99441, 8)

## Olist_Orders Items_Dataset

In [8]:
order_items = pd.read_csv(
    r"C:\Users\DELL\Downloads\olist_order_items_dataset.csv"
)

order_items.shape

(112650, 7)

## Order Payments Dataset

In [9]:
order_payments = pd.read_csv(r"C:\Users\DELL\Downloads\olist_order_payments_dataset.csv")

order_payments.shape

(103886, 5)

In [10]:
import pandas as pd

orders = pd.read_csv(r"C:\Users\DELL\Downloads\olist_orders_dataset.csv")

order_items = pd.read_csv(r"C:\Users\DELL\Downloads\olist_order_items_dataset.csv")

order_payments = pd.read_csv(r"C:\Users\DELL\Downloads\olist_order_payments_dataset.csv")

order_reviews = pd.read_csv(r"C:\Users\DELL\Downloads\olist_order_reviews_dataset.csv")

products = pd.read_csv(r"C:\Users\DELL\Downloads\olist_products_dataset.csv")

customers = pd.read_csv(r"C:\Users\DELL\Downloads\olist_customers_dataset.csv")

sellers = pd.read_csv(r"C:\Users\DELL\Downloads\olist_sellers_dataset.csv")

geolocation = pd.read_csv(r"C:\Users\DELL\Downloads\olist_geolocation_dataset.csv")

category_translation = pd.read_csv(r"C:\Users\DELL\Downloads\product_category_name_translation.csv")

In [11]:
datasets = {
    "Orders": orders,
    "Order Items": order_items,
    "Order Payments": order_payments,
    "Order Reviews": order_reviews,
    "Products": products,
    "Customers": customers,
    "Sellers": sellers,
    "Geolocation": geolocation,
    "Category Translation": category_translation
}

for name, df in datasets.items():
    print(name, ":", df.shape)

Orders : (99441, 8)
Order Items : (112650, 7)
Order Payments : (103886, 5)
Order Reviews : (99224, 7)
Products : (32951, 9)
Customers : (99441, 5)
Sellers : (3095, 4)
Geolocation : (1000163, 5)
Category Translation : (71, 2)

In [12]:
for name, df in datasets.items():
    print("\n", name)
    print(df.info())

 Orders
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None

 Order Items
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None

 Order Payments
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None

 Order Reviews
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
None

 Products
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None

 Customers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

 Sellers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None

 Geolocation
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None

 Category Translation
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
None

### Checking the Missing values

In [13]:
for name, df in datasets.items():
    print("\n" + name)
    print(df.isnull().sum())

Orders
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Order Items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Order Payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Order Reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Products
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Category Translation
product_category_name            0
product_category_name_english    0
dtype: int64

#### Convert date columns

In [15]:
date_columns = {
    "orders": [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ],
    "order_items": ["shipping_limit_date"],
    "order_reviews": [
        "review_creation_date",
        "review_answer_timestamp"
    ]
}

for column in date_columns["orders"]:
    orders[column] = pd.to_datetime(orders[column])

order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"]
)

for column in date_columns["order_reviews"]:
    order_reviews[column] = pd.to_datetime(order_reviews[column])

In [16]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

### Check duplicate records

In [17]:
for name, df in datasets.items():
    print(name, "→", df.duplicated().sum(), "duplicate rows")

Orders → 0 duplicate rows
Order Items → 0 duplicate rows
Order Payments → 0 duplicate rows
Order Reviews → 0 duplicate rows
Products → 0 duplicate rows
Customers → 0 duplicate rows
Sellers → 0 duplicate rows
Geolocation → 261831 duplicate rows
Category Translation → 0 duplicate rows

### Check unique IDs

In [18]:
print("Orders:", orders["order_id"].nunique())
print("Customers:", customers["customer_id"].nunique())
print("Products:", products["product_id"].nunique())
print("Sellers:", sellers["seller_id"].nunique())
print("Reviews:", order_reviews["review_id"].nunique())

Orders: 99441
Customers: 99441
Products: 32951
Sellers: 3095
Reviews: 98410

In [19]:
order_reviews[order_reviews["review_id"].duplicated(keep=False)].sort_values("review_id").head(20)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21,2017-09-26 03:27:47
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
54832,017808d29fd1f942d97e50184dfb4c13,8daaa9e99d60fbba579cc1c3e3bfae01,5,NaN,NaN,2018-03-02,2018-03-05 01:43:30
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,NaN,NaN,2018-03-02,2018-03-05 01:43:30
20621,0254bd905dc677a6078990aad3331a36,5bf226cf882c5bf4247f89a97c86f273,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
89712,0288d42bef3dfe36930740c9588a570f,33d8795f04dd631f3480d7aaf90da3dc,3,NaN,NaN,2017-07-29,2017-07-31 17:11:04
94851,0288d42bef3dfe36930740c9588a570f,f889a5a0b44adc29c5465b99395ac3c1,3,NaN,NaN,2017-07-29,2017-07-31 17:11:04
47495,02aa7f5f75e964e3c7efa59a1f515281,d8e17d5f7dacf0970d316e7c03e741e8,3,NaN,NaN,2017-07-27,2017-07-29 15:09:50
95860,02aa7f5f75e964e3c7efa59a1f515281,db92613c074f00e53066388d48ad7512,3,NaN,NaN,2017-07-27,2017-07-29 15:09:50
71165,034528cb00b6bc981847acafbdf2ae0b,e1e8e3bca903de27e9a1c72b5a5795e0,1,NaN,NaN,2017-05-14,2017-05-15 02:17:38
81094,034528cb00b6bc981847acafbdf2ae0b,3d3742a96f24a8fe4e2e57628807e476,1,NaN,NaN,2017-05-14,2017-05-15 02:17:38
1988,03a6a25db577d0689440933055111897,2acfdc5131ff2cf4433e668454c9784c,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15,2017-12-16 01:32:18
9013,03a6a25db577d0689440933055111897,3fde8b7313af6b37b84b5c7594d7add0,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15,2017-12-16 01:32:18
21587,0467560f511c516ddaa54a60edb0c291,0c995611a99f81268d859184a416f1db,5,NaN,NaN,2017-02-09,2017-02-14 15:58:44
24901,0467560f511c516ddaa54a60edb0c291,55b2e390d5d80ada31ad1b795ebeb087,5,NaN,NaN,2017-02-09,2017-02-14 15:58:44

In [20]:
order_reviews["review_id"].nunique()

98410

### Check order-level relationships

In [21]:
review_counts = order_reviews.groupby("order_id")["review_id"].nunique()

review_counts.value_counts().sort_index()

review_id
1    98126
2      543
3        4
Name: count, dtype: int64

### Data-quality check: numeric values.

In [22]:
print("Order Items - Price <= 0:", (order_items["price"] <= 0).sum())
print("Order Items - Freight < 0:", (order_items["freight_value"] < 0).sum())
print("Payments - Payment Value <= 0:", (order_payments["payment_value"] <= 0).sum())

Order Items - Price <= 0: 0
Order Items - Freight < 0: 0
Payments - Payment Value <= 0: 9

In [ ]:
Result
Price ≤ 0: 0 → all item prices are positive.
Freight < 0: 0 → no negative freight values.
Payment Value ≤ 0: 9 → these need investigation.

In [23]:
order_payments[order_payments["payment_value"] <= 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

### Check product dimensions

In [24]:
print("Weight <= 0:", (products["product_weight_g"] <= 0).sum())
print("Length <= 0:", (products["product_length_cm"] <= 0).sum())
print("Height <= 0:", (products["product_height_cm"] <= 0).sum())
print("Width <= 0:", (products["product_width_cm"] <= 0).sum())

Weight <= 0: 4
Length <= 0: 0
Height <= 0: 0
Width <= 0: 0

In [25]:
products[products["product_weight_g"] <= 0]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,51.0,529.0,1.0,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,48.0,528.0,1.0,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0

In [27]:
## Next steps

### 1. Validate relationships between datasets

In [29]:
# Relationship validation

checks = {
    "Order Items → Orders":
        (~order_items["order_id"].isin(orders["order_id"])).sum(),

    "Order Items → Products":
        (~order_items["product_id"].isin(products["product_id"])).sum(),

    "Order Items → Sellers":
        (~order_items["seller_id"].isin(sellers["seller_id"])).sum(),

    "Orders → Customers":
        (~orders["customer_id"].isin(customers["customer_id"])).sum(),

    "Payments → Orders":
        (~order_payments["order_id"].isin(orders["order_id"])).sum(),

    "Reviews → Orders":
        (~order_reviews["order_id"].isin(orders["order_id"])).sum(),

    "Products → Category Translation":
        (~products["product_category_name"]
         .dropna()
         .isin(category_translation["product_category_name"])).sum()
}

for relationship, missing in checks.items():
    print(f"{relationship}: {missing} missing")

Order Items → Orders: 0 missing
Order Items → Products: 0 missing
Order Items → Sellers: 0 missing
Orders → Customers: 0 missing
Payments → Orders: 0 missing
Reviews → Orders: 0 missing
Products → Category Translation: 13 missing

In [30]:
missing_categories = (
    products.loc[
        products["product_category_name"].notna() &
        ~products["product_category_name"].isin(
            category_translation["product_category_name"]
        ),
        "product_category_name"
    ]
    .unique()
)

print("Missing category translations:", len(missing_categories))
print(missing_categories)

Missing category translations: 2
['pc_gamer' 'portateis_cozinha_e_preparadores_de_alimentos']

Create business-analysis columns

We'll now create metrics that directly support your project:

Order Revenue
Delivery Days
Delivery Delay
On-Time / Late Delivery
Freight % of Order Value
Order Month / Year
Review Category

In [31]:
order_items["order_value"] = (
    order_items["price"] + order_items["freight_value"]
)

order_items[["price", "freight_value", "order_value"]].head()

    price  freight_value  order_value
0   58.90          13.29        72.19
1  239.90          19.93       259.83
2  199.00          17.87       216.87
3   12.99          12.79        25.78
4  199.90          18.14       218.04

In [33]:
orders["delivery_days"] = (
    orders["order_delivered_customer_date"]
    - orders["order_purchase_timestamp"]
).dt.days

orders["delivery_delay_days"] = (
    orders["order_delivered_customer_date"]
    - orders["order_estimated_delivery_date"]
).dt.days

orders[
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "delivery_days",
        "delivery_delay_days"
    ]
].head()

,order_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18,8.0,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13,13.0,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04,9.0,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-11-18 19:28:06,2017-12-02 00:28:42,2017-12-15,13.0,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-13 21:18:39,2018-02-16 18:17:02,2018-02-26,2.0,-10.0

### Create an On-Time/Late status

In [34]:
orders["delivery_performance"] = orders["delivery_delay_days"].apply(
    lambda x: "Late" if x > 0
    else "On Time" if x == 0
    else "Early" if x < 0
    else "Not Delivered"
)

orders[
    ["order_id", "delivery_delay_days", "delivery_performance"]
].head()

                           order_id  delivery_delay_days delivery_performance
0  e481f51cbdc54678b7cc49136f2d6af7                 -8.0                Early
1  53cdb2fc8bc7dce0b6741e2150273451                 -6.0                Early
2  47770eb9100c2d0c44946d9cf07ec65d                -18.0                Early
3  949d5b44dbf5de918fe9c16f97b45f8a                -13.0                Early
4  ad21c59c0840e6cb83a9ceb5573f8159                -10.0                Early

In [35]:
order_items["freight_percentage"] = (
    order_items["freight_value"] / order_items["order_value"]
) * 100

order_items[
    ["price", "freight_value", "order_value", "freight_percentage"]
].head()

    price  freight_value  order_value  freight_percentage
0   58.90          13.29        72.19           18.409752
1  239.90          19.93       259.83            7.670400
2  199.00          17.87       216.87            8.239959
3   12.99          12.79        25.78           49.612102
4  199.90          18.14       218.04            8.319574

In [36]:
# ============================================================
# 1. ORDER-LEVEL VALUE
# ============================================================

order_value_summary = (
    order_items.groupby("order_id", as_index=False)
    .agg(
        total_order_value=("order_value", "sum"),
        total_freight_value=("freight_value", "sum"),
        total_item_price=("price", "sum"),
        item_count=("order_id", "count")
    )
)

order_value_summary["freight_percentage"] = (
    order_value_summary["total_freight_value"]
    / order_value_summary["total_order_value"]
) * 100


# ============================================================
# 2. ORDER DATE FEATURES
# ============================================================

orders["order_year"] = (
    orders["order_purchase_timestamp"].dt.year
)

orders["order_month"] = (
    orders["order_purchase_timestamp"].dt.month
)

orders["order_month_name"] = (
    orders["order_purchase_timestamp"].dt.strftime("%b")
)

orders["order_year_month"] = (
    orders["order_purchase_timestamp"]
    .dt.to_period("M")
    .astype(str)
)


# ============================================================
# 3. PAYMENT SUMMARY
# ============================================================

payment_summary = (
    order_payments.groupby("order_id", as_index=False)
    .agg(
        total_payment_value=("payment_value", "sum"),
        payment_count=("payment_sequential", "count")
    )
)

payment_type_summary = (
    order_payments.groupby("order_id")["payment_type"]
    .first()
    .reset_index()
    .rename(columns={"payment_type": "primary_payment_type"})
)


# ============================================================
# 4. REVIEW CATEGORY
# ============================================================

def classify_review(score):
    if score >= 4:
        return "Positive"
    elif score == 3:
        return "Neutral"
    else:
        return "Negative"


order_reviews["review_category"] = (
    order_reviews["review_score"]
    .apply(classify_review)
)


# ============================================================
# 5. REVIEW SUMMARY AT ORDER LEVEL
# ============================================================

review_summary = (
    order_reviews.groupby("order_id", as_index=False)
    .agg(
        average_review_score=("review_score", "mean"),
        review_count=("review_id", "count")
    )
)

review_summary["review_category"] = (
    review_summary["average_review_score"]
    .apply(
        lambda x:
        "Positive" if x >= 4
        else "Neutral" if x == 3
        else "Negative"
    )
)


# ============================================================
# 6. DELIVERY INDICATORS
# ============================================================

orders["is_delivered"] = (
    orders["order_status"] == "delivered"
)

orders["is_late"] = (
    orders["delivery_delay_days"] > 0
)

orders["is_early"] = (
    orders["delivery_delay_days"] < 0
)


# ============================================================
# 7. CHECK EVERYTHING
# ============================================================

print("Order Value Summary:")
print(order_value_summary.head())

print("\nPayment Summary:")
print(payment_summary.head())

print("\nPayment Type Summary:")
print(payment_type_summary.head())

print("\nReview Summary:")
print(review_summary.head())

print("\nOrders with derived columns:")
print(
    orders[
        [
            "order_id",
            "order_year",
            "order_month",
            "order_year_month",
            "delivery_days",
            "delivery_delay_days",
            "delivery_performance",
            "is_delivered",
            "is_late",
            "is_early"
        ]
    ].head()
)

Order Value Summary:
                           order_id  total_order_value  total_freight_value  \
0  00010242fe8c5a6d1ba2dd792cb16214              72.19                13.29
1  00018f77f2f0320c557190d7a144bdd3             259.83                19.93
2  000229ec398224ef6ca0657da4fc703e             216.87                17.87
3  00024acbcdf0a6daa1e931b038114c75              25.78                12.79
4  00042b26cf59d7ce69dfabb4e55b4fd9             218.04                18.14

   total_item_price  item_count  freight_percentage
0             58.90           1           18.409752
1            239.90           1            7.670400
2            199.00           1            8.239959
3             12.99           1           49.612102
4            199.90           1            8.319574

Payment Summary:
                           order_id  total_payment_value  payment_count
0  00010242fe8c5a6d1ba2dd792cb16214                72.19              1
1  00018f77f2f0320c557190d7a144bdd3               259.83              1
2  000229ec398224ef6ca0657da4fc703e               216.87              1
3  00024acbcdf0a6daa1e931b038114c75                25.78              1
4  00042b26cf59d7ce69dfabb4e55b4fd9               218.04              1

Payment Type Summary:
                           order_id primary_payment_type
0  00010242fe8c5a6d1ba2dd792cb16214          credit_card
1  00018f77f2f0320c557190d7a144bdd3          credit_card
2  000229ec398224ef6ca0657da4fc703e          credit_card
3  00024acbcdf0a6daa1e931b038114c75          credit_card
4  00042b26cf59d7ce69dfabb4e55b4fd9          credit_card

Review Summary:
                           order_id  average_review_score  review_count  \
0  00010242fe8c5a6d1ba2dd792cb16214                   5.0             1
1  00018f77f2f0320c557190d7a144bdd3                   4.0             1
2  000229ec398224ef6ca0657da4fc703e                   5.0             1
3  00024acbcdf0a6daa1e931b038114c75                   4.0             1
4  00042b26cf59d7ce69dfabb4e55b4fd9                   5.0             1

  review_category
0        Positive
1        Positive
2        Positive
3        Positive
4        Positive

Orders with derived columns:
                           order_id  order_year  order_month order_year_month  \
0  e481f51cbdc54678b7cc49136f2d6af7        2017           10          2017-10
1  53cdb2fc8bc7dce0b6741e2150273451        2018            7          2018-07
2  47770eb9100c2d0c44946d9cf07ec65d        2018            8          2018-08
3  949d5b44dbf5de918fe9c16f97b45f8a        2017           11          2017-11
4  ad21c59c0840e6cb83a9ceb5573f8159        2018            2          2018-02

   delivery_days  delivery_delay_days delivery_performance  is_delivered  \
0            8.0                 -8.0                Early          True
1           13.0                 -6.0                Early          True
2            9.0                -18.0                Early          True
3           13.0                -13.0                Early          True
4            2.0                -10.0                Early          True

   is_late  is_early
0    False      True
1    False      True
2    False      True
3    False      True
4    False      True

In [37]:
# ============================================================
# OVERALL E-COMMERCE BUSINESS PERFORMANCE
# ============================================================

total_orders = orders["order_id"].nunique()

delivered_orders = (
    orders["order_status"] == "delivered"
).sum()

total_order_value = (
    order_value_summary["total_order_value"].sum()
)

average_order_value = (
    order_value_summary["total_order_value"].mean()
)

total_freight = (
    order_value_summary["total_freight_value"].sum()
)

average_freight_percentage = (
    order_value_summary["freight_percentage"].mean()
)

late_orders = (
    orders["delivery_performance"] == "Late"
).sum()

early_orders = (
    orders["delivery_performance"] == "Early"
).sum()

on_time_orders = (
    orders["delivery_performance"] == "On Time"
).sum()

average_delivery_days = (
    orders.loc[
        orders["delivery_days"].notna(),
        "delivery_days"
    ].mean()
)

average_review_score = (
    order_reviews["review_score"].mean()
)


# ============================================================
# DISPLAY
# ============================================================

print("Total Orders:", total_orders)
print("Delivered Orders:", delivered_orders)
print("Total Order Value:", round(total_order_value, 2))
print("Average Order Value:", round(average_order_value, 2))
print("Total Freight:", round(total_freight, 2))
print("Average Freight %:", round(average_freight_percentage, 2))
print("Late Orders:", late_orders)
print("Early Orders:", early_orders)
print("On-Time Orders:", on_time_orders)
print("Average Delivery Days:", round(average_delivery_days, 2))
print("Average Review Score:", round(average_review_score, 2))

Total Orders: 99441
Delivered Orders: 96478
Total Order Value: 15843553.24
Average Order Value: 160.58
Total Freight: 2251909.54
Average Freight %: 20.88
Late Orders: 6535
Early Orders: 88649
On-Time Orders: 1292
Average Delivery Days: 12.09
Average Review Score: 4.09

In [38]:
# ============================================================
# MONTHLY ORDER VALUE & ORDER VOLUME
# ============================================================

monthly_performance = (
    orders[["order_id", "order_year_month"]]
    .merge(
        order_value_summary[
            ["order_id", "total_order_value"]
        ],
        on="order_id",
        how="left"
    )
    .groupby("order_year_month", as_index=False)
    .agg(
        total_orders=("order_id", "nunique"),
        total_order_value=("total_order_value", "sum"),
        average_order_value=("total_order_value", "mean")
    )
    .sort_values("order_year_month")
)


# ============================================================
# HIGHEST / LOWEST MONTHS
# ============================================================

highest_value_month = monthly_performance.loc[
    monthly_performance["total_order_value"].idxmax()
]

lowest_value_month = monthly_performance.loc[
    monthly_performance["total_order_value"].idxmin()
]

highest_order_volume_month = monthly_performance.loc[
    monthly_performance["total_orders"].idxmax()
]

lowest_order_volume_month = monthly_performance.loc[
    monthly_performance["total_orders"].idxmin()
]


# ============================================================
# DISPLAY
# ============================================================

print("MONTHLY PERFORMANCE")
print(monthly_performance)

print("\nHighest Order Value Month:")
print(highest_value_month)

print("\nLowest Order Value Month:")
print(lowest_value_month)

print("\nHighest Order Volume Month:")
print(highest_order_volume_month)

print("\nLowest Order Volume Month:")
print(lowest_order_volume_month)

MONTHLY PERFORMANCE
   order_year_month  total_orders  total_order_value  average_order_value
0           2016-09             4             354.75           118.250000
1           2016-10           324           56808.84           184.444286
2           2016-12             1              19.62            19.620000
3           2017-01           800          137188.49           173.876413
4           2017-02          1780          286280.62           165.193664
5           2017-03          2682          432048.59           163.592802
6           2017-04          2404          412422.24           172.489435
7           2017-05          3700          586190.95           160.161462
8           2017-06          3245          502963.04           156.345365
9           2017-07          4026          584971.62           147.385140
10          2017-08          4331          668204.60           155.649802
11          2017-09          4285          720398.91           169.785272
12          2017-10          4631          769312.37           168.413391
13          2017-11          7544         1179143.77           158.253090
14          2017-12          5673          863547.23           153.546805
15          2018-01          7269         1107301.89           153.365913
16          2018-02          6728          986908.96           147.431873
17          2018-03          7211         1155126.82           160.702117
18          2018-04          6939         1159698.04           167.248059
19          2018-05          6873         1149781.82           167.777881
20          2018-06          6167         1022677.11           166.019011
21          2018-07          6292         1058728.03           168.775391
22          2018-08          6512         1003308.47           155.503483
23          2018-09            16             166.46           166.460000
24          2018-10             4               0.00                  NaN

Highest Order Value Month:
order_year_month          2017-11
total_orders                 7544
total_order_value      1179143.77
average_order_value     158.25309
Name: 13, dtype: object

Lowest Order Value Month:
order_year_month       2018-10
total_orders                 4
total_order_value          0.0
average_order_value        NaN
Name: 24, dtype: object

Highest Order Volume Month:
order_year_month          2017-11
total_orders                 7544
total_order_value      1179143.77
average_order_value     158.25309
Name: 13, dtype: object

Lowest Order Volume Month:
order_year_month       2016-12
total_orders                 1
total_order_value        19.62
average_order_value      19.62
Name: 2, dtype: object

In [39]:
# ============================================================
# FILTER TO MEANINGFUL / COMPLETE ANALYSIS PERIOD
# ============================================================

monthly_analysis = monthly_performance[
    monthly_performance["order_year_month"].between(
        "2017-01", "2018-08"
    )
].copy()


# ============================================================
# YEARLY PERFORMANCE
# ============================================================

orders["order_year"] = (
    orders["order_purchase_timestamp"].dt.year
)

yearly_performance = (
    orders[orders["order_year"].isin([2017, 2018])]
    [["order_id", "order_year"]]
    .merge(
        order_value_summary[
            ["order_id", "total_order_value"]
        ],
        on="order_id",
        how="left"
    )
    .groupby("order_year", as_index=False)
    .agg(
        total_orders=("order_id", "nunique"),
        total_order_value=("total_order_value", "sum"),
        average_order_value=("total_order_value", "mean")
    )
)


# ============================================================
# 2017 vs 2018 CHANGE
# ============================================================

value_2017 = yearly_performance.loc[
    yearly_performance["order_year"] == 2017,
    "total_order_value"
].iloc[0]

value_2018 = yearly_performance.loc[
    yearly_performance["order_year"] == 2018,
    "total_order_value"
].iloc[0]

orders_2017 = yearly_performance.loc[
    yearly_performance["order_year"] == 2017,
    "total_orders"
].iloc[0]

orders_2018 = yearly_performance.loc[
    yearly_performance["order_year"] == 2018,
    "total_orders"
].iloc[0]

value_growth = (
    (value_2018 - value_2017) / value_2017
) * 100

order_growth = (
    (orders_2018 - orders_2017) / orders_2017
) * 100


# ============================================================
# DISPLAY
# ============================================================

print("MONTHLY ANALYSIS PERIOD")
print(monthly_analysis)

print("\nYEARLY PERFORMANCE")
print(yearly_performance)

print("\n2017 → 2018 Order Value Change:",
      round(value_growth, 2), "%")

print("2017 → 2018 Order Volume Change:",
      round(order_growth, 2), "%")

MONTHLY ANALYSIS PERIOD
   order_year_month  total_orders  total_order_value  average_order_value
3           2017-01           800          137188.49           173.876413
4           2017-02          1780          286280.62           165.193664
5           2017-03          2682          432048.59           163.592802
6           2017-04          2404          412422.24           172.489435
7           2017-05          3700          586190.95           160.161462
8           2017-06          3245          502963.04           156.345365
9           2017-07          4026          584971.62           147.385140
10          2017-08          4331          668204.60           155.649802
11          2017-09          4285          720398.91           169.785272
12          2017-10          4631          769312.37           168.413391
13          2017-11          7544         1179143.77           158.253090
14          2017-12          5673          863547.23           153.546805
15          2018-01          7269         1107301.89           153.365913
16          2018-02          6728          986908.96           147.431873
17          2018-03          7211         1155126.82           160.702117
18          2018-04          6939         1159698.04           167.248059
19          2018-05          6873         1149781.82           167.777881
20          2018-06          6167         1022677.11           166.019011
21          2018-07          6292         1058728.03           168.775391
22          2018-08          6512         1003308.47           155.503483

YEARLY PERFORMANCE
   order_year  total_orders  total_order_value  average_order_value
0        2017         45101         7142672.43           160.225048
1        2018         54011         8643697.60           160.738217

2017 → 2018 Order Value Change: 21.01 %
2017 → 2018 Order Volume Change: 19.76 %

In [40]:
# ============================================================
# PRODUCT CATEGORY PERFORMANCE
# ============================================================

category_performance = (
    order_items
    .merge(
        products[
            ["product_id", "product_category_name"]
        ],
        on="product_id",
        how="left"
    )
    .merge(
        category_translation,
        on="product_category_name",
        how="left"
    )
)


# ============================================================
# USE ENGLISH CATEGORY NAME WHERE AVAILABLE
# OTHERWISE KEEP ORIGINAL CATEGORY NAME
# ============================================================

category_performance["category"] = (
    category_performance["product_category_name_english"]
    .fillna(category_performance["product_category_name"])
)


# ============================================================
# AGGREGATE CATEGORY METRICS
# ============================================================

category_summary = (
    category_performance
    .groupby("category", as_index=False)
    .agg(
        total_items=("order_item_id", "count"),
        total_order_value=("order_value", "sum"),
        total_freight=("freight_value", "sum"),
        average_item_price=("price", "mean"),
        unique_orders=("order_id", "nunique")
    )
)


# ============================================================
# ADD CATEGORY SHARE
# ============================================================

category_summary["order_value_share"] = (
    category_summary["total_order_value"]
    / category_summary["total_order_value"].sum()
) * 100


# ============================================================
# TOP 10 CATEGORIES BY ORDER VALUE
# ============================================================

top_categories = (
    category_summary
    .sort_values("total_order_value", ascending=False)
    .head(10)
)


print("TOP 10 CATEGORIES BY ORDER VALUE")
print(top_categories)


# ============================================================
# TOP 10 CATEGORIES BY NUMBER OF ITEMS
# ============================================================

top_volume_categories = (
    category_summary
    .sort_values("total_items", ascending=False)
    .head(10)
)

print("\nTOP 10 CATEGORIES BY ITEM VOLUME")
print(top_volume_categories)

TOP 10 CATEGORIES BY ORDER VALUE
                 category  total_items  total_order_value  total_freight  \
43          health_beauty         9670         1441248.07      182566.73
72          watches_gifts         5991         1305541.61      100535.93
7          bed_bath_table        11115         1241681.72      204693.04
67         sports_leisure         8641         1156656.48      168607.51
15  computers_accessories         7827         1059272.40      147318.08
39        furniture_decor         8334          902511.79      172749.30
49             housewares         6964          778397.77      146149.11
20             cool_stuff         3796          719329.95       84039.10
5                    auto         4235          685384.32       92664.21
42           garden_tools         4347          584219.21       98962.75

    average_item_price  unique_orders  order_value_share
43          130.163531           8836           9.217588
72          201.135984           5624           8.349669
7            93.296327           9417           7.941250
67          114.344285           7720           7.397466
15          116.513903           6689           6.774640
39           87.564494           6449           5.772068
49           90.788148           5884           4.978289
20          167.357969           3632           4.600518
5           139.957523           3897           4.383416
42          111.630196           3518           3.736409

TOP 10 CATEGORIES BY ITEM VOLUME
                 category  total_items  total_order_value  total_freight  \
7          bed_bath_table        11115         1241681.72      204693.04
43          health_beauty         9670         1441248.07      182566.73
67         sports_leisure         8641         1156656.48      168607.51
39        furniture_decor         8334          902511.79      172749.30
15  computers_accessories         7827         1059272.40      147318.08
49             housewares         6964          778397.77      146149.11
72          watches_gifts         5991         1305541.61      100535.93
70              telephony         4545          394883.32       71215.79
42           garden_tools         4347          584219.21       98962.75
5                    auto         4235          685384.32       92664.21

    average_item_price  unique_orders  order_value_share
7            93.296327           9417           7.941250
43          130.163531           8836           9.217588
67          114.344285           7720           7.397466
39           87.564494           6449           5.772068
15          116.513903           6689           6.774640
49           90.788148           5884           4.978289
72          201.135984           5624           8.349669
70           71.213978           4199           2.525500
42          111.630196           3518           3.736409
5           139.957523           3897           4.383416

In [41]:
# ============================================================
# SELLER PERFORMANCE
# ============================================================

seller_performance = (
    order_items
    .merge(
        sellers[
            ["seller_id", "seller_zip_code_prefix",
             "seller_city", "seller_state"]
        ],
        on="seller_id",
        how="left"
    )
)


# ============================================================
# SELLER SUMMARY
# ============================================================

seller_summary = (
    seller_performance
    .groupby(
        [
            "seller_id",
            "seller_city",
            "seller_state"
        ],
        as_index=False
    )
    .agg(
        total_items=("order_item_id", "count"),
        unique_orders=("order_id", "nunique"),
        total_order_value=("order_value", "sum"),
        total_freight=("freight_value", "sum"),
        average_item_price=("price", "mean")
    )
)


# ============================================================
# ORDER VALUE SHARE
# ============================================================

seller_summary["order_value_share"] = (
    seller_summary["total_order_value"]
    / seller_summary["total_order_value"].sum()
) * 100


# ============================================================
# TOP 10 SELLERS BY ORDER VALUE
# ============================================================

top_sellers_value = (
    seller_summary
    .sort_values(
        "total_order_value",
        ascending=False
    )
    .head(10)
)

print("TOP 10 SELLERS BY ORDER VALUE")
print(top_sellers_value)


# ============================================================
# TOP 10 SELLERS BY ITEM VOLUME
# ============================================================

top_sellers_volume = (
    seller_summary
    .sort_values(
        "total_items",
        ascending=False
    )
    .head(10)
)

print("\nTOP 10 SELLERS BY ITEM VOLUME")
print(top_sellers_volume)

TOP 10 SELLERS BY ORDER VALUE
                             seller_id       seller_city seller_state  \
857   4869f7a5dfa277a7dca6462dcf3b52b2           guariba           SP
1535  7c67e1448b00f6e969d365cea6b010ab   itaquaquecetuba           SP
1013  53243585a1d6dc2643021fd1853d8905  lauro de freitas           BA
881   4a3ca9315b744ce9f8e9374361493884          ibitinga           SP
3024  fa1c13f2614d7b5c4749cbc52fecda94            sumare           SP
2643  da8622b14eb17ae2831f4ac5b9dab84a        piracicaba           SP
1560  7e93a43ef30c4f03f38b393420bc753a           barueri           SP
192   1025f0e2d44d7041d6cf58b6550e0bfa         sao paulo           SP
1505  7a67c85e85bb2ce8582c35f2203ad736         sao paulo           SP
1824  955fee9216a65b617aa5c0531780ce60         sao paulo           SP

      total_items  unique_orders  total_order_value  total_freight  \
857          1156           1132          249640.70       20168.07
1535         1364            982          239536.44       51612.55
1013          410            358          235856.68       13080.63
881          1987           1806          235539.96       35067.04
3024          586            585          204084.73       10042.70
2643         1551           1314          185192.32       24955.75
1560          340            336          182754.05        6322.18
192          1428            915          172860.69       33892.14
1505         1171           1160          162648.38       20902.85
1824         1499           1287          160602.68       25430.98

      average_item_price  order_value_share
857           198.505735           1.575661
1535          137.774113           1.511886
1013          543.356220           1.488660
881           100.892260           1.486661
3024          331.129744           1.288125
2643          103.311779           1.168881
1560          518.917265           1.153492
192            97.316912           1.091047
1505          121.046567           1.026590
1824           90.174583           1.013678

TOP 10 SELLERS BY ITEM VOLUME
                             seller_id            seller_city seller_state  \
1235  6560211a19b47992c3666cc44a7e94c0              sao paulo           SP
881   4a3ca9315b744ce9f8e9374361493884               ibitinga           SP
368   1f50f920176fa81dab994f9023523100  sao jose do rio preto           SP
2481  cc419e0650a3c5ba77189a1882b7556a            santo andre           SP
2643  da8622b14eb17ae2831f4ac5b9dab84a             piracicaba           SP
1824  955fee9216a65b617aa5c0531780ce60              sao paulo           SP
192   1025f0e2d44d7041d6cf58b6550e0bfa              sao paulo           SP
1535  7c67e1448b00f6e969d365cea6b010ab        itaquaquecetuba           SP
2836  ea8482cd71df3c1969d7b9473ff13abc              sao paulo           SP
1505  7a67c85e85bb2ce8582c35f2203ad736              sao paulo           SP

      total_items  unique_orders  total_order_value  total_freight  \
1235         2033           1854          151265.77       27960.94
881          1987           1806          235539.96       35067.04
368          1931           1404          142104.98       35165.77
2481         1775           1706          129957.41       25668.99
2643         1551           1314          185192.32       24955.75
1824         1499           1287          160602.68       25430.98
192          1428            915          172860.69       33892.14
1535         1364            982          239536.44       51612.55
2836         1203           1146           54722.29       17544.77
1505         1171           1160          162648.38       20902.85

      average_item_price  order_value_share
1235           60.651663           0.954746
881           100.892260           1.486661
368            55.380223           0.896926
2481           58.754039           0.820254
2643          103.311779           1.168881
1824           90.174583           1.013678
192            97.316912           1.091047
1535          137.774113           1.511886
2836           30.904007           0.345392
1505          121.046567           1.026590

In [42]:
# ============================================================
# DELIVERY PERFORMANCE ANALYSIS
# ============================================================

delivery_summary = (
    orders["delivery_performance"]
    .value_counts()
    .reset_index()
)

delivery_summary.columns = [
    "delivery_performance",
    "order_count"
]

delivery_summary["percentage"] = (
    delivery_summary["order_count"]
    / delivery_summary["order_count"].sum()
) * 100


# ============================================================
# AVERAGE DELIVERY METRICS
# ============================================================

avg_delivery_days = orders["delivery_days"].mean()

avg_delay_days = orders["delivery_delay_days"].mean()

late_orders = orders[
    orders["delivery_performance"] == "Late"
]

average_late_delay = late_orders[
    "delivery_delay_days"
].mean()


# ============================================================
# LATE ORDERS BY YEAR
# ============================================================

late_by_year = (
    orders[orders["delivery_performance"] == "Late"]
    .groupby("order_year")
    .size()
    .reset_index(name="late_orders")
)


# ============================================================
# DISPLAY
# ============================================================

print("DELIVERY PERFORMANCE")
print(delivery_summary)

print("\nAverage Delivery Days:",
      round(avg_delivery_days, 2))

print("Average Delivery Delay:",
      round(avg_delay_days, 2))

print("Average Late Delivery Delay:",
      round(average_late_delay, 2))

print("\nLATE ORDERS BY YEAR")
print(late_by_year)

DELIVERY PERFORMANCE
  delivery_performance  order_count  percentage
0                Early        88649   89.147334
1                 Late         6535    6.571736
2        Not Delivered         2965    2.981668
3              On Time         1292    1.299263

Average Delivery Days: 12.09
Average Delivery Delay: -11.88
Average Late Delivery Delay: 10.62

LATE ORDERS BY YEAR
   order_year  late_orders
0        2016            3
1        2017         2453
2        2018         4079

In [43]:
# ============================================================
# DELIVERY PERFORMANCE vs CUSTOMER REVIEWS
# ============================================================

delivery_reviews = (
    orders[
        [
            "order_id",
            "delivery_performance",
            "delivery_days",
            "delivery_delay_days"
        ]
    ]
    .merge(
        review_summary[
            [
                "order_id",
                "average_review_score"
            ]
        ],
        on="order_id",
        how="inner"
    )
)


# ============================================================
# AVERAGE REVIEW SCORE BY DELIVERY PERFORMANCE
# ============================================================

review_by_delivery = (
    delivery_reviews
    .groupby("delivery_performance", as_index=False)
    .agg(
        orders=("order_id", "nunique"),
        average_review_score=("average_review_score", "mean")
    )
    .sort_values(
        "average_review_score",
        ascending=False
    )
)


# ============================================================
# REVIEW SCORE BY LATE / NOT LATE
# ============================================================

delivery_reviews["late_flag"] = (
    delivery_reviews["delivery_performance"] == "Late"
)

review_by_late_flag = (
    delivery_reviews
    .groupby("late_flag", as_index=False)
    .agg(
        orders=("order_id", "nunique"),
        average_review_score=("average_review_score", "mean")
    )
)


# ============================================================
# DISPLAY
# ============================================================

print("REVIEW SCORE BY DELIVERY PERFORMANCE")
print(review_by_delivery)

print("\nREVIEW SCORE: LATE vs NOT LATE")
print(review_by_late_flag)

REVIEW SCORE BY DELIVERY PERFORMANCE
  delivery_performance  orders  average_review_score
0                Early   88168              4.294151
3              On Time    1280              4.035547
1                 Late    6382              2.271937
2        Not Delivered    2843              1.753254

REVIEW SCORE: LATE vs NOT LATE
   late_flag  orders  average_review_score
0      False   92291              4.212292
1       True    6382              2.271937

In [44]:
# ============================================================
# DELIVERY PERFORMANCE BY PRODUCT CATEGORY
# ============================================================

category_delivery = (
    order_items[
        [
            "order_id",
            "product_id"
        ]
    ]
    .merge(
        category_performance[
            [
                "product_id",
                "category"
            ]
        ].drop_duplicates("product_id"),
        on="product_id",
        how="left"
    )
    .merge(
        orders[
            [
                "order_id",
                "delivery_performance",
                "delivery_delay_days"
            ]
        ],
        on="order_id",
        how="left"
    )
)


# ============================================================
# CATEGORY DELIVERY SUMMARY
# ============================================================

category_delivery_summary = (
    category_delivery
    .groupby("category", as_index=False)
    .agg(
        total_items=("product_id", "count"),
        late_items=(
            "delivery_performance",
            lambda x: (x == "Late").sum()
        ),
        average_delay_days=(
            "delivery_delay_days",
            "mean"
        )
    )
)


# ============================================================
# LATE DELIVERY RATE
# ============================================================

category_delivery_summary["late_rate"] = (
    category_delivery_summary["late_items"]
    / category_delivery_summary["total_items"]
) * 100


# ============================================================
# FILTER OUT VERY SMALL CATEGORIES
# ============================================================

category_delivery_summary_filtered = (
    category_delivery_summary[
        category_delivery_summary["total_items"] >= 100
    ]
    .sort_values(
        "late_rate",
        ascending=False
    )
)


# ============================================================
# TOP CATEGORIES WITH HIGHEST LATE RATE
# ============================================================

print("CATEGORIES WITH HIGHEST LATE DELIVERY RATE")
print(
    category_delivery_summary_filtered.head(15)
)

CATEGORIES WITH HIGHEST LATE DELIVERY RATE
                     category  total_items  late_items  average_delay_days  \
4                       audio          364          42          -10.149171
12         christmas_supplies          153          15          -12.053333
47               home_confort          434          40           -9.811189
33    fashion_underwear_beach          131          12          -10.929134
10            books_technical          267          21          -11.307985
57           office_furniture         1691         133          -11.845923
26                electronics         2767         207          -11.139978
6                        baby         3065         229          -11.646546
43              health_beauty         9670         717          -11.970107
18  construction_tools_lights          304          22          -11.222591
56        musical_instruments          680          48          -11.483871
72              watches_gifts         5991         422          -11.920437
40      furniture_living_room          503          35          -11.800000
7              bed_bath_table        11115         770          -11.656167
39            furniture_decor         8334         574          -12.399510

    late_rate
4   11.538462
12   9.803922
47   9.216590
33   9.160305
10   7.865169
57   7.865169
26   7.481026
6    7.471452
43   7.414685
18   7.236842
56   7.058824
72   7.043899
40   6.958250
7    6.927575
39   6.887449

In [45]:
# ============================================================
# CATEGORY-LEVEL DELIVERY PERFORMANCE
# ORDER-LEVEL METRICS
# ============================================================

category_order_delivery = (
    order_items[
        ["order_id", "product_id"]
    ]
    .merge(
        products[
            ["product_id", "product_category_name"]
        ],
        on="product_id",
        how="left"
    )
    .merge(
        category_translation,
        on="product_category_name",
        how="left"
    )
)

# English category where available
category_order_delivery["category"] = (
    category_order_delivery["product_category_name_english"]
    .fillna(
        category_order_delivery["product_category_name"]
    )
)

# One category per order-item
category_order_delivery = (
    category_order_delivery[
        ["order_id", "category"]
    ]
    .drop_duplicates()
)

# Add delivery information
category_order_delivery = (
    category_order_delivery
    .merge(
        orders[
            [
                "order_id",
                "delivery_performance",
                "delivery_delay_days"
            ]
        ],
        on="order_id",
        how="left"
    )
)


# ============================================================
# CATEGORY DELIVERY SUMMARY
# ============================================================

category_delivery_final = (
    category_order_delivery
    .groupby("category", as_index=False)
    .agg(
        total_orders=("order_id", "nunique"),
        late_orders=(
            "delivery_performance",
            lambda x: (x == "Late").sum()
        ),
        average_delivery_delay=(
            "delivery_delay_days",
            "mean"
        )
    )
)

# Late delivery rate
category_delivery_final["late_rate"] = (
    category_delivery_final["late_orders"]
    / category_delivery_final["total_orders"]
) * 100


# ============================================================
# REMOVE VERY SMALL CATEGORIES
# ============================================================

category_delivery_final = (
    category_delivery_final[
        category_delivery_final["total_orders"] >= 100
    ]
    .sort_values(
        "late_rate",
        ascending=False
    )
)


# ============================================================
# TOP CATEGORIES BY LATE RATE
# ============================================================

print("TOP CATEGORIES BY ORDER-LEVEL LATE RATE")
print(
    category_delivery_final.head(15)
)

TOP CATEGORIES BY ORDER-LEVEL LATE RATE
                           category  total_orders  late_orders  \
4                             audio           350           41
47                     home_confort           397           37
33          fashion_underwear_beach           121           11
10                  books_technical           260           21
57                 office_furniture          1273          101
6                              baby          2885          226
12               christmas_supplies           128           10
26                      electronics          2550          192
43                    health_beauty          8836          650
40            furniture_living_room           422           31
56              musical_instruments           628           46
7                    bed_bath_table          9417          689
17  construction_tools_construction           748           54
72                    watches_gifts          5624          406
5                              auto          3897          278

    average_delivery_delay  late_rate
4               -10.043103  11.714286
47               -9.762755   9.319899
33              -10.504274   9.090909
10              -11.332031   8.076923
57              -11.823764   7.934014
6               -11.495550   7.833622
12              -12.184000   7.812500
26              -11.016289   7.529412
43              -11.980923   7.356270
40              -11.734300   7.345972
56              -11.477905   7.324841
7               -11.393658   7.316555
17              -11.097826   7.219251
72              -11.799381   7.219061
5               -11.213179   7.133693

In [46]:
# ============================================================
# PAYMENT METHOD ANALYSIS
# ============================================================

payment_analysis = (
    order_payments
    .groupby("payment_type", as_index=False)
    .agg(
        total_transactions=("order_id", "count"),
        unique_orders=("order_id", "nunique"),
        total_payment_value=("payment_value", "sum"),
        average_payment_value=("payment_value", "mean")
    )
)

# Payment share by transaction count
payment_analysis["transaction_share"] = (
    payment_analysis["total_transactions"]
    / payment_analysis["total_transactions"].sum()
) * 100

# Payment share by value
payment_analysis["value_share"] = (
    payment_analysis["total_payment_value"]
    / payment_analysis["total_payment_value"].sum()
) * 100

payment_analysis = payment_analysis.sort_values(
    "total_payment_value",
    ascending=False
)

print("PAYMENT METHOD ANALYSIS")
print(payment_analysis)

PAYMENT METHOD ANALYSIS
  payment_type  total_transactions  unique_orders  total_payment_value  \
1  credit_card               76795          76505          12542084.19
0       boleto               19784          19784           2869361.27
4      voucher                5775           3866            379436.87
2   debit_card                1529           1528            217989.79
3  not_defined                   3              3                 0.00

   average_payment_value  transaction_share  value_share
1             163.319021          73.922376    78.344584
0             145.034435          19.043952    17.923569
4              65.703354           5.558978     2.370166
2             142.570170           1.471806     1.361681
3               0.000000           0.002888     0.000000

In [47]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print(df.dtypes)

============================================================
Orders
============================================================
order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
delivery_days                           float64
delivery_delay_days                     float64
delivery_performance                     object
order_year                                int32
order_month                               int32
order_month_name                         object
order_year_month                         object
is_delivered                               bool
is_late                                    bool
is_early                                   bool
dtype: object

============================================================
Order Items
============================================================
order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
order_value                   float64
freight_percentage            float64
dtype: object

============================================================
Order Payments
============================================================
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

============================================================
Order Reviews
============================================================
review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
review_category                    object
dtype: object

============================================================
Products
============================================================
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

============================================================
Customers
============================================================
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

============================================================
Sellers
============================================================
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

============================================================
Geolocation
============================================================
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

============================================================
Category Translation
============================================================
product_category_name            object
product_category_name_english    object
dtype: object